somehow opam completion only works when init is sourced in zshrc

diff --git a/runcoms/zshrc b/runcoms/zshrc
--- a/runcoms/zshrc
+++ b/runcoms/zshrc
@@ -46,6 +46,10 @@ alias sgfr='autostash git svn rebase'
 alias sgc='git commit --verbose && git svn dcommit'
 
 ## OCaml
+. $HOME/.opam/opam-init/init.zsh > /dev/null 2> /dev/null || true
+export OPAMKEEPBUILDDIR=true # support Merlin's Locate on all libs
+export OCAMLPARAM="_,bin-annot=1"
+export OCAMLRUNPARAM=b # enable backtraces on error
 alias utop='utop -require batteries -require cil'
 alias ocaml='rlwrap -H ~/.ocaml_history -D 2 -i -s 10000 ocamlfind batteries/ocaml'
 function ocr(){
